# Generated by Django 4.2.9 on 2025-04-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0003_rename_album_title_82714c_idx_api_album_title_17e95f_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queue",
            name="current_track",
        ),
    ]
