# Generated by Django 4.2.9 on 2025-04-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_queue_current_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="playstate",
            name="context_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="playstate",
            name="context_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("playlist", "Playlist"),
                    ("album", "Album"),
                    ("artist", "Artist"),
                    ("liked", "Liked Songs"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="playstate",
            name="position_in_context",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
