# Generated by Django 4.2.9 on 2025-04-30 07:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_playstate_context_id_playstate_context_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playstate",
            name="volume",
            field=models.PositiveIntegerField(
                default=70,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="playstate",
            name="context_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="playstate",
            name="current_track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.track",
            ),
        ),
    ]
