# Generated by Django 4.2.9 on 2025-05-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_track_duration_alter_track_play_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playstate",
            name="context_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
