# Generated by Django 4.2.9 on 2025-05-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_playstate_context_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="image_page",
            field=models.ImageField(blank=True, null=True, upload_to="artists/"),
        ),
    ]
