# Generated by Django 4.2.9 on 2025-05-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_artist_image_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queue",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="queuetrack",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="queuetrack",
            name="queue",
        ),
        migrations.RemoveField(
            model_name="queuetrack",
            name="track",
        ),
        migrations.DeleteModel(
            name="PlayHistory",
        ),
        migrations.DeleteModel(
            name="Queue",
        ),
        migrations.DeleteModel(
            name="QueueTrack",
        ),
    ]
